const lanes=[['D','前方高能'],['F','名场面'],['J','下次一定'],['K','好耶！']],beat=468.75,len=32000;
let difficulty=1,phase='ready',notes=[],start=0,score=0,combo=0,maxCombo=0,perfect=0,good=0,miss=0,muted=false,raf,audio;
const $=id=>document.getElementById(id),show=(id,on)=>$(id).classList.toggle('hidden',!on);
function beatmap(){const a=[];let id=0;for(let b=4;b<68;b++){if(difficulty===0&&b%2)continue;let l=(b*3+Math.floor(b/4))%4;a.push({id:id++,l,t:b*beat,hit:false});if(difficulty===2&&b%4===3)a.push({id:id++,l:(l+2)%4,t:b*beat,hit:false})}return a}
function beep(f){if(muted)return;audio=audio||new AudioContext();const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=f;g.gain.setValueAtTime(.09,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.07);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+.07)}
function setup(){const root=$('lanes');root.innerHTML='';lanes.forEach((x,i)=>{const b=document.createElement('button');b.className='lane l'+i;b.innerHTML=`<small>${x[1]}</small><b>${x[0]}</b>`;b.setAttribute('aria-label',`${x[0]}键轨道 ${x[1]}`);b.addEventListener('pointerdown',()=>hit(i));root.appendChild(b)})}
function reset(){notes=beatmap();score=combo=maxCombo=perfect=good=miss=0;update();$('progress').style.width='0';$('judge').textContent=''}
function begin(){reset();phase='count';show('startPanel',false);show('resultPanel',false);show('countPanel',true);show('gamePanel',false);document.querySelectorAll('[data-diff]').forEach(b=>b.disabled=true);let n=3;$('countText').textContent=n;const t=setInterval(()=>{n--;if(n){$('countText').textContent=n}else{clearInterval(t);$('countText').textContent='GO!';setTimeout(()=>{show('countPanel',false);show('gamePanel',true);phase='play';start=performance.now();raf=requestAnimationFrame(loop)},350)}},650)}
function hit(l){if(phase!=='play')return;const now=performance.now()-start,x=notes.filter(n=>!n.hit&&n.l===l).sort((a,b)=>Math.abs(a.t-now)-Math.abs(b.t-now))[0],d=x?Math.abs(x.t-now):999;if(!x||d>180){beep(80);return}x.hit=true;const p=d<85;p?perfect++:good++;combo++;maxCombo=Math.max(maxCombo,combo);score+=(p?1000:600)+Math.min(combo,50)*12;judge(p?'PERFECT':'GOOD');beep(p?660:440);update()}
function judge(t){const j=$('judge');j.className='judge '+t;j.innerHTML=`${t}<small>${t==='MISS'?'节拍溜走了':'+ '+combo+' COMBO'}</small>`;j.animate([{opacity:0,transform:'translateX(-50%) scale(.5)'},{opacity:1,transform:'translateX(-50%) scale(1.12)'},{transform:'translateX(-50%) scale(1)'}],{duration:350})}
function loop(){const now=performance.now()-start;notes.forEach(n=>{if(!n.hit&&now-n.t>180){n.hit=true;miss++;combo=0;judge('MISS')}});document.querySelectorAll('.note').forEach(n=>n.remove());notes.filter(n=>!n.hit&&n.t>=now-200&&n.t<=now+2400).forEach(n=>{const e=document.createElement('div');e.className='note n'+n.l;e.style.left=(n.l*25+2.5)+'%';e.style.top=Math.min(82,Math.max(-8,82-(n.t-now)/2200*86))+'%';e.textContent=lanes[n.l][1];$('lanes').appendChild(e)});$('progress').style.width=Math.min(100,now/len*100)+'%';$('time').textContent=Math.ceil(Math.max(0,len-now)/1000)+'s';update();if(now>=len)finish();else raf=requestAnimationFrame(loop)}
function update(){const energy=Math.min(100,Math.round(perfect*2.2+good*1.2));$('score').textContent=String(score).padStart(6,'0');$('combo').textContent=combo;$('perfect').textContent=perfect;$('good').textContent=good;$('miss').textContent=miss;$('energy').innerHTML=Array.from({length:12},(_,i)=>`<i class="${energy>=(i+1)*8?'on':''}"></i>`).join('');$('energyText').textContent=`⚡ ${Math.round(energy*.24)} / 24`;$('energyHint').textContent=`再积攒 ${Math.max(0,Math.ceil((100-energy)/2))} 个节拍充满能量`;const best=Math.max(score,+(localStorage.best||0));$('best').textContent=best.toLocaleString();return energy}
function finish(){cancelAnimationFrame(raf);phase='result';show('gamePanel',false);show('resultPanel',true);document.querySelectorAll('[data-diff]').forEach(b=>b.disabled=false);const total=Math.max(1,perfect+good+miss),acc=Math.round((perfect+good*.65)/total*100),energy=update();localStorage.best=Math.max(score,+(localStorage.best||0));$('rank').textContent=energy>=90?'梗 王':energy>=65?'高 能':'入 坑';$('finalScore').textContent=score.toLocaleString();$('accuracy').textContent=acc+'%';$('maxCombo').textContent=maxCombo}
document.querySelectorAll('[data-diff]').forEach(b=>b.onclick=()=>{difficulty=+b.dataset.diff;document.querySelectorAll('[data-diff]').forEach(x=>x.classList.toggle('on',x===b))});$('startBtn').onclick=$('replayBtn').onclick=begin;$('mute').onclick=()=>{muted=!muted;$('mute').textContent=muted?'🔇':'♫'};addEventListener('keydown',e=>{const i=lanes.findIndex(x=>x[0]===e.key.toUpperCase());if(i>=0){e.preventDefault();hit(i)}if(e.key===' '&&phase!=='play'&&phase!=='count')begin()});setup();update();
