const extraStyle=document.createElement('link');extraStyle.rel='stylesheet';extraStyle.href='songs.css';document.head.appendChild(extraStyle);
const lanes=[['D','前方高能'],['F','名场面'],['J','下次一定'],['K','好耶！']],diffKeys=['easy','normal','hard'];
let difficulty=1,songIndex=0,phase='ready',notes=[],score=0,combo=0,maxCombo=0,perfect=0,good=0,miss=0,muted=false,raf,countTimer;
const $=id=>document.getElementById(id),music=$('music'),show=(id,on)=>$(id).classList.toggle('hidden',!on),song=()=>SONGS[songIndex],chart=()=>song().charts[diffKeys[difficulty]],now=()=>music.currentTime*1000+(+(localStorage.rhythmOffset||0));

function setupLanes(){const root=$('lanes');root.innerHTML='';lanes.forEach((x,i)=>{const b=document.createElement('button');b.className='lane l'+i;b.innerHTML=`<small>${x[1]}</small><b>${x[0]}</b>`;b.setAttribute('aria-label',`${x[0]}键轨道 ${x[1]}`);b.addEventListener('pointerdown',()=>hit(i));root.appendChild(b)})}
function renderSongs(){const list=$('songList');list.innerHTML='';SONGS.forEach((s,i)=>{const card=document.createElement('button');card.className='song-card'+(i===songIndex?' selected':'');card.style.setProperty('--a',s.colors[0]);card.style.setProperty('--b',s.colors[1]);card.innerHTML=`<span class="disc"><i>♫</i></span><span class="song-copy"><small>TRACK ${String(i+1).padStart(2,'0')}</small><strong>${s.title}</strong><em>${s.subtitle}</em><span class="tags"><i>${s.bpm} BPM</i><i>${Math.floor(s.duration/60)}:${String(Math.round(s.duration%60)).padStart(2,'0')}</i><i>${s.charts.normal.length} NOTES</i></span></span><b class="pick">${i===songIndex?'已选择':'选择'}</b>`;card.onclick=()=>selectSong(i);list.appendChild(card)})}
function selectSong(i){if(phase==='play'||phase==='count')return;music.pause();songIndex=i;music.src=encodeURI(song().file);music.load();renderSongs();syncSelected();update()}
function syncSelected(){$('selectedTitle').innerHTML=`${song().title}<br><i>踩准节拍</i>`;$('selectedMeta').textContent=`♪ ${song().bpm} BPM · ${chart().length} NOTES · ${['轻松','高能','鬼畜'][difficulty]}`;$('playingTitle').textContent=`TRACK ${String(songIndex+1).padStart(2,'0')} · ${song().title}`}
function reset(){notes=chart().map((n,id)=>({id,t:n[0],l:n[1],hit:false}));score=combo=maxCombo=perfect=good=miss=0;music.currentTime=0;update();$('progress').style.width='0';$('judge').textContent=''}
function begin(){clearInterval(countTimer);cancelAnimationFrame(raf);reset();phase='count';show('startPanel',false);show('resultPanel',false);show('countPanel',true);show('gamePanel',false);lock(true);music.volume=muted?0:1;music.play().then(()=>{music.pause();music.currentTime=0}).catch(()=>{});let n=3;$('countText').textContent=n;countTimer=setInterval(()=>{n--;if(n){$('countText').textContent=n}else{clearInterval(countTimer);$('countText').textContent='GO!';setTimeout(startMusic,320)}},650)}
function startMusic(){show('countPanel',false);show('gamePanel',true);phase='play';music.currentTime=0;music.volume=muted?0:1;music.play().then(()=>raf=requestAnimationFrame(loop)).catch(()=>{phase='ready';show('gamePanel',false);show('startPanel',true);lock(false);$('selectedMeta').textContent='音频播放被浏览器拦截，请再次点击开始'})}
function hit(l){if(phase!=='play')return;const t=now(),x=notes.filter(n=>!n.hit&&n.l===l).sort((a,b)=>Math.abs(a.t-t)-Math.abs(b.t-t))[0],d=x?Math.abs(x.t-t):999;if(!x||d>190)return;x.hit=true;const p=d<=90;p?perfect++:good++;combo++;maxCombo=Math.max(maxCombo,combo);score+=(p?1000:620)+Math.min(combo,60)*15;judge(p?'PERFECT':'GOOD');update()}
function judge(t){const j=$('judge');j.className='judge '+t;j.innerHTML=`${t}<small>${t==='MISS'?'节拍溜走了':'+ '+combo+' COMBO'}</small>`;j.animate([{opacity:0,transform:'translateX(-50%) scale(.5)'},{opacity:1,transform:'translateX(-50%) scale(1.12)'},{transform:'translateX(-50%) scale(1)'}],{duration:330})}
function loop(){if(phase!=='play')return;const t=now();notes.forEach(n=>{if(!n.hit&&t-n.t>200){n.hit=true;miss++;combo=0;judge('MISS')}});document.querySelectorAll('.note').forEach(n=>n.remove());notes.filter(n=>!n.hit&&n.t>=t-220&&n.t<=t+2400).forEach(n=>{const e=document.createElement('div');e.className='note n'+n.l;e.style.left=(n.l*25+2.5)+'%';e.style.top=Math.min(82,Math.max(-8,82-(n.t-t)/2200*86))+'%';e.textContent=lanes[n.l][1];$('lanes').appendChild(e)});$('progress').style.width=Math.min(100,t/(song().duration*1000)*100)+'%';$('time').textContent=Math.ceil(Math.max(0,song().duration-music.currentTime))+'s';update();if(music.ended||music.currentTime>=song().duration-.08)finish();else raf=requestAnimationFrame(loop)}
function energyValue(){return Math.min(100,Math.round((perfect+good*.55)/Math.max(1,notes.length)*115))}
function bestKey(){return `best_${song().id}_${diffKeys[difficulty]}`}
function update(){const energy=energyValue();$('score').textContent=String(score).padStart(6,'0');$('combo').textContent=combo;$('perfect').textContent=perfect;$('good').textContent=good;$('miss').textContent=miss;$('energy').innerHTML=Array.from({length:12},(_,i)=>`<i class="${energy>=(i+1)*8?'on':''}"></i>`).join('');$('energyText').textContent=`⚡ ${Math.round(energy*.24)} / 24`;$('energyHint').textContent=energy>=100?'梗能量满载，研究增益已激活！':`完成度 ${energy}% · 继续保持节奏`;$('best').textContent=(+(localStorage[bestKey()]||0)).toLocaleString();return energy}
function finish(){cancelAnimationFrame(raf);music.pause();phase='result';show('gamePanel',false);show('resultPanel',true);lock(false);const total=Math.max(1,perfect+good+miss),acc=Math.round((perfect+good*.65)/total*100),energy=update();localStorage[bestKey()]=Math.max(score,+(localStorage[bestKey()]||0));$('best').textContent=(+localStorage[bestKey()]).toLocaleString();$('rank').textContent=acc>=95?'梗 王':acc>=80?'高 能':acc>=60?'入 坑':'再 练';$('finalScore').textContent=score.toLocaleString();$('accuracy').textContent=acc+'%';$('maxCombo').textContent=maxCombo}
function togglePause(){if(phase==='play'){music.pause();phase='pause';cancelAnimationFrame(raf);show('pauseLayer',true);$('pauseBtn').textContent='▶'}else if(phase==='pause'){phase='play';show('pauseLayer',false);$('pauseBtn').textContent='Ⅱ';music.play();raf=requestAnimationFrame(loop)}}
function lock(on){document.querySelectorAll('[data-diff],.song-card').forEach(b=>b.disabled=on)}
document.querySelectorAll('[data-diff]').forEach(b=>b.onclick=()=>{difficulty=+b.dataset.diff;document.querySelectorAll('[data-diff]').forEach(x=>x.classList.toggle('on',x===b));syncSelected();update()});
$('startBtn').onclick=$('replayBtn').onclick=begin;$('pauseBtn').onclick=togglePause;$('pauseLayer').onclick=togglePause;$('mute').onclick=()=>{muted=!muted;music.volume=muted?0:1;$('mute').textContent=muted?'🔇':'♫'};
addEventListener('keydown',e=>{const i=lanes.findIndex(x=>x[0]===e.key.toUpperCase());if(i>=0){e.preventDefault();hit(i)}if(e.key===' '&&(phase==='ready'||phase==='result'))begin();if(e.key.toUpperCase()==='P'&&(phase==='play'||phase==='pause'))togglePause()});
music.addEventListener('error',()=>{$('selectedMeta').textContent='音频加载失败，请刷新页面重试'});setupLanes();renderSongs();selectSong(0);
